USE [master]
GO

/****** Object:  Database [GBRMetaData]    Script Date: 8/5/2017 11:21:11 AM ******/
CREATE DATABASE [GBRMetaData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GerberMetaData', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\GerberMetaData.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GerberMetaData_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\GerberMetaData_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GBRMetaData] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GBRMetaData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GBRMetaData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GBRMetaData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GBRMetaData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GBRMetaData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GBRMetaData] SET ARITHABORT OFF 
GO

ALTER DATABASE [GBRMetaData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GBRMetaData] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [GBRMetaData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GBRMetaData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GBRMetaData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GBRMetaData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GBRMetaData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GBRMetaData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GBRMetaData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GBRMetaData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GBRMetaData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GBRMetaData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GBRMetaData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GBRMetaData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GBRMetaData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GBRMetaData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GBRMetaData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GBRMetaData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GBRMetaData] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GBRMetaData] SET  MULTI_USER 
GO

ALTER DATABASE [GBRMetaData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GBRMetaData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GBRMetaData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GBRMetaData] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GBRMetaData] SET  READ_WRITE 
GO

